### ISSUE TITLE
namespace support with include

### ISSUE THREAD

**Issue by jnoortheen** [nat-n/poethepoet#110]
It would be good to have support for nested tasks. In a monorepo, subproject's tasks need to be run in their own directory. Calling them from the root directory will be convenient. 

Example: https://taskfile.dev/usage/#including-other-taskfiles , this accepts `dir:` argument as well. That will be used as the workdir for the nested tasks

**Comment by nat-n** [comment]
Hi @jnoortheen, thanks for the feedback. Monorepo support is something I'd like poe to be better at.

Have you tried achieving this with the [include](https://github.com/nat-n/poethepoet#load-tasks-from-another-file) option, combined with the [cwd](https://github.com/nat-n/poethepoet#running-a-task-with-a-specific-working-directory) option?

Does that do what you want or is there something missing? I guess the way `cwd` works is a bit limited here because poe doesn't explicitly keep track of the location of the file the task was defined in, when what you really want is to set something like: `cwd = "${TASK_FILE_DIR}"`, and maybe also to be able to configure this per pyproject.toml rather than per task?

**Comment by jnoortheen** [comment]
@nat-n thanks for the quick reply. I did try `include` option, it would be cumbersome to define the cwd on the included task file. Since I am converting from `taskfile.yml` I expected the `include` to accept a table with `cwd` option. 
It would be easier to call tasks from sub-modules.

**Comment by nat-n** [comment]
Yea, that makes sense. It'll be in the next release soon :)

**Comment by nat-n** [comment]
@jnoortheen  This feature is now available as part of [v0.17.0](https://pypi.org/project/poethepoet/0.17.0/).

**Comment by jnoortheen** [comment]
Looks neat. Thanks!
