### ISSUE TITLE
env file interacts badly with glob

### ISSUE THREAD

**Issue by jwhitaker-gridcog** [nat-n/poethepoet#234]
If I have an envfile
```sh
DB_URL=postgres://user:pass@postgres/db
```
and pyproject
```toml
[poe.task.migrate]
cmd = "migrate -database=${DB_URL}"
envfile = ".env"
```

then everything is fine.

If, however, I include a better password in my env file:

```sh
DB_URL=postgres://user:super-Secret-pass*-with-a-star@postgres/db
```

then `poe` inexplicably starts dropping the `-database` arg to `migrate` completely.

After much doubting of my sanity and lost hours hair pulling, it looks like something somewhere is globbing the '*' in the env var, even though I specifically picked a `cmd` task because I didn't want a shell in the way screwing up stuff like this.

1) it's not clear how to avoid this behaviour: none of `DB_URL=...\*`, `DB_URL="...*"`, `DB_URL='...*'` , `DB_URL=...\\*` seem to work.
2) assuming I'm right and this is globbing-gone-feral, it would be very helpful in this case to print a warning, `no files matched glob expression "...", excluding arguments -database=${DB_URL}`.
3) I really would not ever want globs interpreted out of an env file in the first place if I'm doing things explicitly without a shell, I'm not sure about other use cases but i'd question if globbing here could be disabled completely.

Thanks for maintaining this!
Jarrad

**Comment by nat-n** [comment]
Hi @jwhitaker-gridcog, thanks for the feedback!

The philosophy of poe cmd tasks is to be ["shell like"](https://poethepoet.natn.io/tasks/task_types/cmd.html#shell-like-features) without actually involving a shell — because usually that's quite convenient. Therefore parameter substitution and globing are implemented like a subset of bash. I see now how this can lead to some frustrating surprises around this kind of use case, but I believe there is still a simple way to get what you want :)

Just like in bash, you can disable filename expansion after parameter substitution in cmd tasks with double quotes. So I think the following example should work for you (env and envfile are logically interchangeable for demonstration purposes).

```sh
[tool.poe.tasks.migrate]
cmd = "migrate \"-database=${DB_URL}\""
env = { DB_URL = "postgres://user:super-Secret-pass*-with-a-star@postgres/db"}
```

Note: although in recent versions of poethepoet the cmd task behaviour is explicitly modelled as a subset of bash bash when it comes to variable substitution, quotes, etc I'd previously decided long ago that it was more user friendly in some cases to diverge from bash by resolving non-matching glob patterns to nothing, because it makes tasks like [this one](https://github.com/nat-n/poethepoet/blob/32689ca6252d0da09232087ad8f97ea9337036eb/pyproject.toml#L90) behave more consistently.

**Comment by jwhitaker-gridcog** [comment]
that does work as a workaround, thanks.
I'm not so sure about the divergence from bash.. it makes sense in those cases, but in cases where the user didn't even intend for globbing to be involved, it causes a silent and hard-to-debug failure.

Out of interest, `fish` shell also diverges from bash here for the same sort of scenario you've included, however their behaviour is to loudly fail with `No matches for wildcard "*.noexisty". See \`help expand\`.". This at least clues the user in that globbing is involved. Maybe at least a warning in Poe's case here could be helpful?

**Comment by nat-n** [comment]
@jwhitaker-gridcog I'll take a note of this as a sharp edge to improve when I get around to implementing better handling for warnings.

**Comment by nat-n** [comment]
As of version [0.36.0](https://github.com/nat-n/poethepoet/releases/tag/v0.36.0) poethepoet's default handling of empty glob patterns is changed to align with how bash does it, i.e. unmatched glob patterns are passed through to the command without modification. So this issue should be less likely in future.
