### ISSUE TITLE
Support for `uv` package manager?

### ISSUE THREAD

**Issue by aaronsteers** [nat-n/poethepoet#257]
Our team uses Poe and Poetry together but we're planning to move to `uv` soon. Does Poe support `uv` and/or are there plans to support it in the future?

**Comment by nat-n** [comment]
Hi @aaronsteers,
uv does look pretty neat, though I haven't yet worked with it myself. I suspect it wouldn't be too hard to make poethepoet work well with uv as well. 

In the best case it would be just a matter of implementing another executor class like [this one for poetry](https://github.com/nat-n/poethepoet/blob/main/poethepoet/executor/poetry.py) including some logic to locate the relevant venv for the current uv project and then tweaking [the base class](https://github.com/nat-n/poethepoet/blob/main/poethepoet/executor/base.py#L114) to be able to determine whether the current project uses uv.

I'd be interested to add support for this, though contributions – at least to validate and prototype the idea – would help.

**Comment by nat-n** [comment]
I had a quick look at how uv manages virtual environments, and it turns out that since it does the conventional thing of keeping the the project venv directory at `./.venv` poe doesn't need to know anything about uv specifically to work with uv managed projected! I'll update the docs to clarify this.

So since it looks like **poethepoet already works with uv projects**, I'm going to close this issue. But I'd be interested to know if there are features missing to better integrate with a typical uv based workflow. For instance some accommodation may be required if/when uv adds support for [central management of venvs](https://github.com/astral-sh/uv/issues/1495).

**Comment by aaronsteers** [comment]
Fantastic. Thanks, @nat-n!

**Comment by AKuederle** [comment]
Maybe a small extension to this. `uv` recommends to always use `uv run` to run tasks within the project instead of activating the venv manually. The reason for this is, that `uv run` actually checks all packages are up to date. So first class support for `uv` could include doing that as well.

**Comment by AKuederle** [comment]
I implemented a first version of a uv executor for poe in #271.
