### ISSUE TITLE
Implications of running task with shell?

### ISSUE THREAD

**Issue by connerxyz** [nat-n/poethepoet#31]
I've needed to define a `poe` task that strings together shell commands with `&&`.

```
{ shell = "foo && bar && ..." }
```

How is this different from the non-shell (?) `poe` tasks? What should I be aware of when distributing to other devs on my team (e.g., will it break if they have a different shell... just spitballing this)?

**Comment by nat-n** [comment]
Hi @connerxyz,

At a low level the difference is that cmd uses subprocess.Popen more or less directly with what you give it (with some preprocessing to resolve env variables), whereas shell tasks actually invoke a specific shell process to interpret what you give it. In general this shell should be assumed to be bash, which means that if there is no bash in the local environment then it will fail.

Of course on windows this gets a little complicated since bash isn't a standard part of the environment, so poe will do its best to find bash on the path, or where git bash is usually found. 

There are a few edge cases that need improvement, see #27 #15

**Comment by nat-n** [comment]
Closing stale issue without defined action points.
