### ISSUE TITLE
Task command output redirect does not work

### ISSUE THREAD

**Issue by Tradunsky** [nat-n/poethepoet#58]
Thanks for creating such a convenient tool 🙏🏻 

One thing that is a bit confusing to me is command output redirect does not work:
```bash
>file: pyproject.toml
[tool.poe.tasks]
create-dotenv="echo 'VARIABLE=VALUE' > .env"

> poetry run poe create-dotenv
> ls -l .env
ls: .env: No such file or directory
```

Current workaround: 
```bash
>file: pyproject.toml
[tool.poe.tasks]
create-dotenv="echo 'VARIABLE=VALUE'"

poetry run poe -q create-dotenv > .env
```

However, it does not play with chained tasks :(

**Comment by nat-n** [comment]
Hi @Tradunsky, thanks for the feedback.

The issue here is that by default tasks are of [type cmd](https://github.com/nat-n/poethepoet#types-of-task), meaning they're executed as direct subprocesses (without involving a shell).

You can get what you want (i.e. the ability to use POSIX shell syntax) by defining a task of type shell. You can specify the task type by declaring the task as a subtable, with the task type as the key containing the task content. TOML supports several different way of achieving this, the simplest looks like:

```toml
[tool.poe.tasks]
create-dotenv.shell = "echo 'VARIABLE=VALUE' > .env"
```

You can also [change the default task type](https://github.com/nat-n/poethepoet#change-the-default-task-type)

You'll find more details and examples in the README. I'll close this issue now, but feel free to reply if there's more to it.
